[tool.poetry]
name = "private-journal"
version = "0.1.0"
description = "Сайт для ведения личного дневника."
authors = ["geemoowy <kovylek.ul@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
