# Generated by Django 5.2.4 on 2025-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Введите заголовок записи', max_length=100, verbose_name='Заголовок записи')),
                ('content', models.TextField(help_text='Поделитесь своей записью (текст записи)', verbose_name='Содержание записи')),
                ('mood', models.CharField(blank=True, choices=[('😊', 'Счастье'), ('😟', 'Грусть'), ('😡', 'Злость'), ('😫', 'Усталость'), ('🤩', 'Воодушевление'), ('😮', 'Удивление'), ('😍', 'Влюбленность')], help_text='Выберите ваше настроение', max_length=2, verbose_name='Настроение')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='diary_images/', verbose_name='Картинка')),
                ('is_public', models.BooleanField(default=False, help_text='Является ли запись публичной?', verbose_name='Публичная запись')),
                ('read_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время чтения (мин)')),
            ],
        ),
    ]
