# Generated by Django 5.2.4 on 2025-07-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mood',
            field=models.CharField(blank=True, choices=[('😊', 'Счастье'), ('😂', 'Юмор'), ('😟', 'Грусть'), ('😡', 'Злость'), ('😫', 'Усталость'), ('🤩', 'Воодушевление'), ('😮', 'Удивление'), ('😍', 'Влюбленность')], help_text='Выберите ваше настроение', max_length=2, verbose_name='Настроение'),
        ),
    ]
