# Generated by Django 5.2.4 on 2025-07-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_options_alter_diary_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user',
            new_name='owner',
        ),
    ]
