# Generated by Django 5.2.4 on 2025-07-22 16:07

from django.db import migrations

def set_owner_from_user(apps, schema_editor):
    Diary = apps.get_model('diary', 'Diary')
    for diary in Diary.objects.all():
        if hasattr(diary, 'user') and diary.user:
            diary.owner = diary.user
            diary.save()

class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_rename_user_diary_owner'),
    ]

    operations = [
        migrations.RunPython(set_owner_from_user),
    ]
