# Generated by Django 5.2.4 on 2025-07-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_diary_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'permissions': [('can_view_public_diaries', 'Может просматривать публичные записи'), ('can_delete_public_diaries', 'Может удалять любые публичные записи')], 'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
    ]
