# Generated by Django 5.2.4 on 2025-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'permissions': [('can_delete_public_diaries', 'Может удалять любые публичные записи')], 'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
    ]
